oss_teamproject/boardsite/board/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'user'

urlpatterns = [
    path('', views.main, name="mainpage"),  # 메인 페이지 연결
    path('bulletin', views.bulletin, name="bulletinboard"),  # 게시판 뷰 연결
    path('info', views.userinfo, name="userinfo"),   # 유저 정보 뷰 연결
    path('register', views.register, name="register"), # 회원 가입 페이지로 연결
    path('login', views.login, name='login'), # 로그인 페이지로 연결
    path('logout', views.logout, name='logout') # 로그아웃
]

oss_teamproject/boardsite/boardsite/urls.py
from django.contrib import admin
from django.urls import path, include
# summernote setting
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('board.urls')),
    path('bulletinboard/', include('bulletinboard.urls')),
]

urlpatterns += [path('summernote/', include('django_summernote.urls'))]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

oss_teamproject/boardsite/board/models.py
from django.db import models


class User(models.Model):
    u_id = models.CharField(max_length=40, unique=True, verbose_name='사용자 아이디')
    u_pw = models.CharField(max_length=100, verbose_name='사용자 비밀번호')
    u_name = models.CharField(max_length=20, unique=True, verbose_name='사용자 이름')
    u_phone = models.CharField(max_length=40, unique=True, verbose_name='사용자 번호')
    u_register_date = models.DateTimeField(auto_now_add=True, verbose_name='사용자 계정 생성 시간')

    def __str__(self):
        return self.u_name

    class Meta:
        db_table = 'user'
        verbose_name = '유저 정보'
        verbose_name_plural = '유저 정보'

oss_teamproject/boardsite/board/forms.py
from django import forms
from .models import User
from argon2 import PasswordHasher, exceptions

class LoginForm(forms.Form):
    u_id = forms.CharField(
        max_length=32,
        label='id',
        required=True,
        widget=forms.TextInput(
            attrs={
                'class': 'u-id',
                'placeholder': 'id'
            }
        ),
        error_messages={'required': '아이디를 반드시 입력해주세요!'}

    )
    u_pw = forms.CharField(
        max_length=128,
        label='pw',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'class': 'u-pw',
                'placeholder': 'password'
            }
        ),
        error_messages={'required': '비밀번호를 반드시 입력해주세요!'}
    )

    field_order = [
        'u_id',
        'u_pw',
    ]

    def clean(self):
        cleaned_data = super().clean()

        u_id = cleaned_data.get('u_id', '')
        u_pw = cleaned_data.get('u_pw', '')

        if u_id == '':
            return self.add_error('u_id', '아이디를 반드시 입력해주세요.')
        elif u_pw == '':
            return self.add_error('u_pw', '비밀번호를 다시 입력해주세요.')
        else:
            try:
                user = User.objects.get(u_id=u_id)
            except User.DoesNotExist:
                return self.add_error('u_id','해당 아이디가 존재하지 않습니다.')

            try:
                PasswordHasher().verify(user.u_pw, u_pw)
            except exceptions.VerificationError:
                return self.add_error('u_pw', '비밀번호가 다릅니다.')

            self.login_session = user.u_id

class RegisterForm(forms.ModelForm):
    u_id = forms.CharField(
        label='id',
        required=True,
        widget=forms.TextInput(
            attrs={
                'class': 'u-id',
                'placeholder': '아이디 입력'
            }
        ),
        error_messages={'required': '아이디를 입력해주세요!',
                        'unique' : '이미 존재하는 아이디입니다.'}
    )

    u_pw = forms.CharField(
        label='pw',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'class': 'u-pw',
                'placeholder': '비밀번호 입력'
            }
        ),
        error_messages={'required': '반드시 비밀번호를 입력해주세요!'}
    )

    u_pw_confirm = forms.CharField(
        label='re-pw',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'class': 'u-pw_confirm',
                'placeholder': '비밀번호 확인'
            }
        ),
        error_messages={'required': '비밀번호가 일치하지 않습니다!'}
    )

    u_name = forms.CharField(
        label='name',
        required=True,
        widget=forms.TextInput(
            attrs={
                'class': 'u-name',
                'placeholder': '사용할 이름 입력'
            }
        ),
        error_messages={'required': '반드시 사용할 이름을 입력해주세요!'}
    )

    u_phone = forms.CharField(
        label='phone',
        required=True,
        widget=forms.TextInput(
            attrs={
                'class': 'u-phone',
                'placeholder': '사용자 전화번호 입력'
            }
        ),
        error_messages={'required': '반드시 전화번호를 입력해주세요!',
                        'unique' : '이미 사용 중인 번호입니다.'}
    )

    field_order = [
        'u_id',
        'u_pw',
        'u_pw_confirm',
        'u_name',
        'u_phone'
    ]


    class Meta:
        model = User
        fields = [
            'u_id',
            'u_pw',
            'u_name',
            'u_phone'
        ]


    def clean(self):
        cleaned_data = super().clean()

        u_id = cleaned_data.get('u_id', '')
        u_pw = cleaned_data.get('u_pw', '')
        u_pw_confirm = cleaned_data.get('u_pw_confirm', '')
        u_name = cleaned_data.get('u_name', '')
        u_phone = cleaned_data.get('u_phone', '')

        if u_pw != u_pw_confirm:
            return self.add_error('u_pw_confirm', '비밀번호가 일치하지 않습니다!!')
        elif not (5 <= len(u_id) <= 20):
            return self.add_error('u_id', '아이디는 5~20자로 입력해주세요')
        elif 6 > len(u_pw):
            return self.add_error('u_pw', '보안을 위해 비밀번호는 6자 이상으로 적어주세요')
        else:
            self.u_id = u_id
            self.u_pw = PasswordHasher().hash(u_pw)
            self.u_pw_confirm = u_pw_confirm
            self.u_name = u_name
            self.u_phone = u_phone

oss_teamproject/boardsite/board/views.py
from django.shortcuts import render, redirect
from .models import User
from argon2 import PasswordHasher
from django.http import HttpResponse
from .forms import RegisterForm, LoginForm

# 게시판 프로그램 메인 화면 구현
def main(request):
    login_session = request.session.get('login_session', '')
    context = {'login_session':login_session}
    return render(request, 'board/main.html', context)

# 게시판 화면
def bulletin(request):
    return render(request, 'board/bulletinboard.html')

# 등록된 사용자 정보 보기 (id, 이름, phone number)
def userinfo(request):
    u_list = User.objects.all()
    return render(request, 'board/userinfo.html', {'u_list': u_list})

# 로그인
def login(request):
    loginform = LoginForm()
    context = {'forms': loginform }

    if request.method == 'GET':
        return render(request, 'board/login.html', context)

    elif request.method == 'POST':
        loginform = LoginForm(request.POST)

        if loginform.is_valid():
            request.session['login_session'] = loginform.login_session
            request.session.set_expiry(0)
            return redirect('/')
        else:
            context['forms'] = loginform
            if loginform.errors:
                for value in loginform.errors.values():
                    context['error'] = value
        return render(request, 'board/login.html', context)

# 사용자 정보 등록
def register(request):
    register_form = RegisterForm()
    context = {'forms': register_form}

    if request.method == 'GET':
        return render(request, 'board/register.html', context)

    elif request.method == 'POST':
        register_form = RegisterForm(request.POST)
        if register_form.is_valid():
            user = User(
                u_id = register_form.u_id,
                u_pw = register_form.u_pw,
                u_name = register_form.u_name,
                u_phone = register_form.u_phone
            )
            user.save()
            return redirect('/')
        else:
            context['forms'] = register_form
            if register_form.errors:
                for value in register_form.errors.values():
                    context['error'] = value
        return render(request, 'board/register.html', context)


# 로그아웃
def logout(request):
    request.session.flush()
    return redirect('/')


def hello(request):
    context = {}
    login_session = request.session.get('login_session','')
    if login_session == '':
        context['login_session'] = False
    else:
        context['login_session'] = True
    return render(request, 'board/main.html', context)

oss_teamproject/boardsite/board/templates/board/login.html
{% extends 'board/main.html' %}
{% block contents %}
<div>로그인 페이지</div>
<form action = "" method ="POST">
    {% csrf_token %}

    {% for form in forms %}
    <div>
        <label for = "{{ form.id_for_label }}"> {{ form.label }} </label>
        {{ form }}
    </div>
    {% endfor %}

    {% if error %}
    {{ error }}
    {% endif %}
    <button type="submit" name="login-submit" value="login">로그인</button>
</form>
{% endblock contents %}

oss_teamproject/boardsite/board/templates/board/main.html
<head>
    <h1 style="text-align:center;"> This is main page </h1>
    <style>
        #btn_group button{
            border: 1px solid skyblue;
            background-color: beige;
            color: skyblue;
            padding: 5px;
            border-top-right-radius: 5px;
            border-bottom-right-radius: 5px;
            border-top-left-radius: 5px;
            border-bottom-left-radius: 5px;
        }
        #btn_group button:hover{
            color:white;
            background-color: lightpink;
        }
    </style>
</head>
<body>
<hr>
<h3>DKU OPEN-SOURCE DJANGO PROJECT</h3>
<p>select option below</p>
    <br>
    <div id = "btn_group">
        <button id = "btn_home" style="border: 1px black solid; margin: 5px 0px;"><a href="/">home</a></button>
        <button id = "btn_userinfo" style="border: 1px black solid; margin: 5px 0px;"><a href="http://127.0.0.1:8000/info">유저 정보</a></button>
        <button id = "btn_admin" style="border: 1px black solid; margin: 5px 0px;"><a href="http://127.0.0.1:8000/admin">관리자 페이지</a></button>
        <button id = "btn_bulletin" style="border: 1px black solid; margin: 5px 0px;"><a href="http://127.0.0.1:8000/bulletinboard/">게시판</a></button>
        {% if login_session %}
            <button id = btn_logout" style="border: 1px black solid; margin: 5px 0px;"><a href="{% url 'user:logout' %}">로그아웃</a></button>
        {% else %}
            <button id = "btn_signup" style="border: 1px black solid; margin: 5px 0px;"><a href="http://127.0.0.1:8000/register">회원 가입</a></button>
            <button id = "btn_login" style="border: 1px black solid; margin: 5px 0px;"><a href="http://127.0.0.1:8000/login">로그인</a></button>
        {% endif %}
    </div>
    <hr>
{% block contents %}
{% endblock contents %}
</body>

oss_teamproject/boardsite/board/templates/board/register.html
{% extends 'board/main.html' %}
{% block contents %}
<div>회원가입 페이지</div>
<form action = "" method ="POST">
    {% csrf_token %}

    {% for form in forms %}
    <div>
        <label for = "{{ form.id_for_label }}"> {{ form.label }} </label>
        {{ form }}
    </div>
    {% endfor %}

    {% for form in forms %}
    {{ form.errors }}
    {% endfor %}

    <button type="submit" name="register-submit" value="register">회원가입하기</button>
</form>

{% endblock contents %}

oss_teamproject/boardsite/board/templates/board/userinfo.html
{% extends 'board/main.html' %}
{% block contents %}
<div>User Information page</div>
<hr>
<ul>
    {% if u_list %}
    <table border = '1' bordercolor="black" width = "40%" height = "120">
        <caption style="color: olivedrab"><b>user information</b></caption>
        <thead>
        <tr>
            <th bgcolor = "#a9a9a9" width="30%">user id</th>
            <th bgcolor="#a9a9a9">user name</th>
            <th bgcolor="#a9a9a9">user phone num.</th>
        </tr>
        </thead>
        <tbody>
    {% for i in u_list %}
        <tr>
            <td style="text-align:center;">{{ i.u_id }}</td>
            <td style="text-align:center;">{{ i.u_name }}</td>
            <td style="text-align:center;">{{ i.u_phone }}</td>
        </tr>
    {% endfor %}
        </tbody>
    </table>
    {% endif %}
</ul>
{% endblock contents %}